name: Notify
on:
  schedule:
    - cron: "0 20 * * *" # At 8pm UTC
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Hit the notify server
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
          APP_URL: ${{ secrets.APP_URL }}
        run: |
          curl \
            -H "Title: Daily Check-in" \
            -H "Click: $APP_URL" \
            -d "Click do to your daily check-in" \
            ntfy.sh/$NTFY_TOPIC
